name: multi_window_drop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  # desktop_drop: 
  #   path: packages/desktop_drop
  desktop_multi_window:
    path: packages/desktop_multi_window
  # drag_and_drop_windows:
  #   path: packages/drag_and_drop_windows
  # dragdropwindows: ^0.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
